stages:
    - lint
    - test-build
    - test
    - build
    - deploy

clang-format: # TODO: Use clang format 11, currently the image install clang-format 7.0
    image: gcc:10.2.0
    stage: lint
    before_script: 
        - apt update && apt install -y clang-format
    script:
        - |
            for f in $(find . -regex '.*\.\(h\|hpp\|tpp\|c\|cpp\)'); 
                do clang-format -style=file $f; 
            done
    allow_failure: true
    only:
        refs:
            - master
            - merge_requests
            - external_pull_requests

os-matcher-app-build:
    image: gcc:10.2.0
    stage: test-build
    before_script:
        - |
            apt update \
            && apt install -y cmake ninja-build python3-pip pv \
            && rm -rf /var/lib/apt/lists/*
        - pip3 install conan
        - conan remote add -f ambrosys https://gl.ambrosys.de/api/v4/projects/356/packages/conan
        - conan user --remote ambrosys ci_user -p $CI_JOB_TOKEN
        - echo https://$GITHUB_HTTPS_USERNAME:$GITHUB_HTTPS_PASSWORD@github.com > ~/.git-credentials
        - git config --global credential.helper store
        - git submodule update --init
        - NJOBS=$(nproc) make -C ThirdParty
    script:
        - cmake -Bbuild -H. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_LIBRARY=ON -DBUILD_DOCS=OFF
        - ninja -C build test-if-git-HEAD-has-changed
        - ninja -C build install
        - build/install/bin/ExampleMatcher -h
    cache:
        paths:
            - ~/.conan/
    artifacts:
        paths:
            - build
        expire_in: 1 day
    only:
        refs:
            - master
            - merge_requests
            - external_pull_requests

unit-test:
    image: gcc:10.2.0
    stage: test
    script:
        - build/bin/UnitTestsGraph
    dependencies: 
        - os-matcher-app-build
    only:
        refs:
            - master
            - merge_requests
            - external_pull_requests

build doc:
    image: bibermann/os-matcher:gcc-sphinx
    stage: build
    script:
        - cmake -H. -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_LIBRARY=OFF -DBUILD_DOCS=ON
        - ninja -C build install
    artifacts:
        paths:
            - build
        expire_in: 1 day
    only:
        refs:
            - master
            - merge_requests
            - external_pull_requests

pages:
    image: python:3-slim
    stage: deploy
    variables:
        GIT_STRATEGY: none
        GITHUB_REPO: git@github.com:Ambrosys/os-matcher.git
    before_script:
        - apt-get update
        - apt-get install -y git-all
        - git --version
        - mkdir /root/.ssh
        - cp $GITHUB_DEPLOY_KEY /root/.ssh/id_github
        - cp $GITHUB_DEPLOY_KEY_PUB ~/.ssh/id_github.pub
        - chmod 600 /root/.ssh/id_github
        - |
            cat >>/etc/ssh/ssh_config <<EOL
            Host github.com
                Hostname github.com
                User git
                Port 22
                IdentityFile /root/.ssh/id_github
                IdentitiesOnly yes
                StrictHostKeyChecking no
            EOL
        - cat /etc/ssh/ssh_config
    script:
        - |
            if [ ! -f build/install/doc/html/index.html ]; then
                mkdir -p public
                echo "Build-error." > public/index.html
            else
                rm -rf public
                cp -r build/install/doc/html public
                cp build/install/doc/os-matcher.pdf public/
                rm -rf public/.doctrees
            fi
        - git clone -b gh-pages $GITHUB_REPO github_repo
        - cd github_repo
        - git rm -r .
        - cp -r --no-target-directory ../public .
        - git add .
        - git commit -m "Deploying to gh-pages testing" || true
        - git push $GITHUB_REPO
    dependencies:
        - build doc
    artifacts:
        paths:
            - public
    only:
        refs:
            - master



