image: bibermann/os-matcher:gcc-sphinx

stages:
    - build
    - deploy

build g++:
    stage: build
    before_script:
        - rm -rf build/install
        - rm -rf build/docs/sphinx
        - rm -rf docs/_api
    script:
        - mkdir -p build/install
        - cd build
        - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=ON
        - ninja install
    artifacts:
        paths:
            - build
        expire_in: 1 day

pages:
    image: python:3-slim
    stage: deploy
    variables:
        GIT_STRATEGY: none
    script:
        - |
            if [ ! -f build/install/doc/html/index.html ]; then
                mkdir -p public
                echo "Build-error." > public/index.html
            else
                rm -rf public
                cp -r build/install/doc/html public
                rm -rf public/.doctrees
            fi
    dependencies:
        - build g++
    artifacts:
        paths:
            - public
    only:
        refs:
            - master
